[package]
name = "data-fetch-project"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
ureq = { version = "2.6", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }